services:
  - type: web
    name: mindspace-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://minduser:%2EMindSpace100%2E@cluster1.8kovn.mongodb.net/mindspace?retryWrites=true&w=majority&appName=Cluster1
      - key: SECRET_KEY
        value: N3V3RG1V3UP
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "120"
      - key: ENCRYPTION_KEY
        value: supersecretpassword1234567890
